import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoMigration1777714381068 implements MigrationInterface {
    name = 'AutoMigration1777714381068'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "rol" ("id_rol" SERIAL NOT NULL, "nombre_rol" character varying(50) NOT NULL, "descripcion" character varying(255), CONSTRAINT "UQ_25cd1dbb608db5a46969d902f53" UNIQUE ("nombre_rol"), CONSTRAINT "PK_0b42a30072d57ccfad9949218da" PRIMARY KEY ("id_rol"))`);
        await queryRunner.query(`CREATE TABLE "sesion" ("id_sesion" SERIAL NOT NULL, "id_usuario" integer NOT NULL, "token_hash" character varying(255) NOT NULL, "fecha_creacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "fecha_expiracion" TIMESTAMP WITH TIME ZONE NOT NULL, "ip_address" inet, "activa" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_25f520935e8570102c469357dfc" PRIMARY KEY ("id_sesion"))`);
        await queryRunner.query(`CREATE TYPE "public"."material_guardado_tipo_contenido_enum" AS ENUM('proyecto', 'articulo', 'hilo')`);
        await queryRunner.query(`CREATE TABLE "material_guardado" ("id_guardado" SERIAL NOT NULL, "id_usuario" integer NOT NULL, "tipo_contenido" "public"."material_guardado_tipo_contenido_enum" NOT NULL, "id_contenido" integer NOT NULL, "fecha_guardado" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_5a50eb462debd1a68def8f11df9" PRIMARY KEY ("id_guardado"))`);
        await queryRunner.query(`CREATE TABLE "usuario" ("id_usuario" SERIAL NOT NULL, "nombre" character varying(100) NOT NULL, "apellido" character varying(100) NOT NULL, "email" character varying(150) NOT NULL, "password_hash" character varying(255) NOT NULL, "fecha_registro" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "activo" boolean NOT NULL DEFAULT true, "foto_perfil" character varying(255), "carnet" character varying(20), "semestre" integer, "failed_login_attempts" integer NOT NULL DEFAULT '0', "lock_until" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_2863682842e688ca198eb25c124" UNIQUE ("email"), CONSTRAINT "PK_dd52716c2652e0e23c15530c695" PRIMARY KEY ("id_usuario"))`);
        await queryRunner.query(`CREATE TABLE "archivo_proyecto" ("id_archivo" SERIAL NOT NULL, "id_proyecto" integer NOT NULL, "nombre_archivo" character varying(255) NOT NULL, "ruta_archivo" character varying(500) NOT NULL, "tipo_mime" character varying(100), "tamanio_bytes" bigint, "fecha_subida" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_5077b4ab81894603f74be1561e0" PRIMARY KEY ("id_archivo"))`);
        await queryRunner.query(`CREATE TABLE "curaduria" ("id_curaduria" SERIAL NOT NULL, "id_proyecto" integer NOT NULL, "id_auxiliar" integer, "comentario_auxiliar" text, "fecha_destacado" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "activo" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_be08e479aab1bdc7cc7b6478006" UNIQUE ("id_proyecto"), CONSTRAINT "REL_be08e479aab1bdc7cc7b647800" UNIQUE ("id_proyecto"), CONSTRAINT "PK_2c01094865c81fb0a37de821e94" PRIMARY KEY ("id_curaduria"))`);
        await queryRunner.query(`CREATE TABLE "etiqueta" ("id_etiqueta" SERIAL NOT NULL, "nombre" character varying(100) NOT NULL, "color" character varying(7) NOT NULL DEFAULT '#3498db', CONSTRAINT "UQ_c24e444690deb02aa6202719e56" UNIQUE ("nombre"), CONSTRAINT "PK_9fe868fc5036d07f153b9c997d6" PRIMARY KEY ("id_etiqueta"))`);
        await queryRunner.query(`CREATE TYPE "public"."proyecto_estado_enum" AS ENUM('borrador', 'pendiente', 'publicado', 'archivado')`);
        await queryRunner.query(`CREATE TABLE "proyecto" ("id_proyecto" SERIAL NOT NULL, "titulo" character varying(200) NOT NULL, "descripcion" text, "stack_tecnologico" jsonb, "fecha_publicacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "estado" "public"."proyecto_estado_enum" NOT NULL DEFAULT 'borrador', "id_usuario" integer NOT NULL, "id_categoria" integer, "vistas" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_5ecc7af27ab7fa5ed5243d437c4" PRIMARY KEY ("id_proyecto"))`);
        await queryRunner.query(`CREATE TYPE "public"."categoria_area_tecnica_enum" AS ENUM('Desarrollo', 'IA', 'Infraestructura', 'Bases_de_Datos', 'Redes', 'Otro')`);
        await queryRunner.query(`CREATE TABLE "categoria" ("id_categoria" SERIAL NOT NULL, "nombre" character varying(150) NOT NULL, "descripcion" text, "area_tecnica" "public"."categoria_area_tecnica_enum" NOT NULL, "id_categoria_padre" integer, CONSTRAINT "PK_950063d23664f5aaec4dcada4d4" PRIMARY KEY ("id_categoria"))`);
        await queryRunner.query(`CREATE TYPE "public"."reporte_estado_enum" AS ENUM('pendiente', 'resuelto', 'desestimado')`);
        await queryRunner.query(`CREATE TABLE "reporte" ("id_reporte" SERIAL NOT NULL, "razon" character varying(255) NOT NULL, "descripcion" text, "fecha_reporte" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "estado" "public"."reporte_estado_enum" NOT NULL DEFAULT 'pendiente', "id_reportador" integer NOT NULL, "id_hilo" integer, "id_comentario" integer, "id_proyecto" integer, "id_moderador" integer, CONSTRAINT "PK_47bdb6e5b218eb2f5e205dfbbb9" PRIMARY KEY ("id_reporte"))`);
        await queryRunner.query(`CREATE TYPE "public"."hilo_foro_estado_enum" AS ENUM('abierto', 'cerrado', 'archivado')`);
        await queryRunner.query(`CREATE TABLE "hilo_foro" ("id_hilo" SERIAL NOT NULL, "titulo" character varying(255) NOT NULL, "contenido" text NOT NULL, "fecha_creacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id_usuario" integer NOT NULL, "id_categoria" integer, "estado" "public"."hilo_foro_estado_enum" NOT NULL DEFAULT 'abierto', "vistas" integer NOT NULL DEFAULT '0', "fijado" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_0a18d36244b4cc4b8fd3fa0b55d" PRIMARY KEY ("id_hilo"))`);
        await queryRunner.query(`CREATE TABLE "comentario" ("id_comentario" SERIAL NOT NULL, "contenido" text NOT NULL, "fecha_creacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id_usuario" integer NOT NULL, "id_hilo" integer, "id_articulo" integer, "id_comentario_padre" integer, "eliminado" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_ec595a4d999244c9ccfc170b3f1" PRIMARY KEY ("id_comentario"))`);
        await queryRunner.query(`CREATE TYPE "public"."articulo_estado_enum" AS ENUM('borrador', 'publicado', 'archivado')`);
        await queryRunner.query(`CREATE TABLE "articulo" ("id_articulo" SERIAL NOT NULL, "titulo" character varying(255) NOT NULL, "contenido_html" text NOT NULL, "resumen" text, "fecha_publicacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id_autor" integer NOT NULL, "estado" "public"."articulo_estado_enum" NOT NULL DEFAULT 'borrador', "imagen_portada" character varying(500), CONSTRAINT "PK_174d815d571a267ee980240d6dc" PRIMARY KEY ("id_articulo"))`);
        await queryRunner.query(`CREATE TYPE "public"."valoracion_tipo_enum" AS ENUM('upvote', 'downvote')`);
        await queryRunner.query(`CREATE TABLE "valoracion" ("id_valoracion" SERIAL NOT NULL, "tipo" "public"."valoracion_tipo_enum" NOT NULL, "id_usuario" integer NOT NULL, "id_hilo" integer, "id_comentario" integer, "id_articulo" integer, "fecha" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_0d6c8f3cb04816e3df8648f64f4" PRIMARY KEY ("id_valoracion"))`);
        await queryRunner.query(`CREATE TABLE "proyecto_vista" ("id_vista" SERIAL NOT NULL, "id_proyecto" integer NOT NULL, "id_usuario" integer NOT NULL, "fecha_visita" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "uq_proyecto_vista_usuario" UNIQUE ("id_proyecto", "id_usuario"), CONSTRAINT "PK_a9428ccf9b15cfba2dace59b1e8" PRIMARY KEY ("id_vista"))`);
        await queryRunner.query(`CREATE TABLE "password_reset" ("id_reset" SERIAL NOT NULL, "id_usuario" integer NOT NULL, "token_hash" character varying(255) NOT NULL, "fecha_creacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "fecha_expiracion" TIMESTAMP WITH TIME ZONE NOT NULL, "usado" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_3b2564b17efeabdfbb293b8c8da" PRIMARY KEY ("id_reset"))`);
        await queryRunner.query(`CREATE TABLE "usuario_suspension" ("id_suspension" SERIAL NOT NULL, "id_usuario" integer NOT NULL, "id_admin" integer NOT NULL, "razon" character varying(255) NOT NULL, "detalle" text, "fecha_inicio" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "fecha_fin" TIMESTAMP WITH TIME ZONE, "activo" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_36d73861e4e332d5d80402efef5" PRIMARY KEY ("id_suspension"))`);
        await queryRunner.query(`CREATE TABLE "admin_audit" ("id_audit" SERIAL NOT NULL, "accion" character varying(120) NOT NULL, "entidad" character varying(120) NOT NULL, "entidad_id" integer, "detalles" jsonb, "fecha_accion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id_admin" integer NOT NULL, CONSTRAINT "PK_d43c4fc22ef2bd96bf9769d0611" PRIMARY KEY ("id_audit"))`);
        await queryRunner.query(`CREATE TABLE "usuario_rol" ("id_usuario" integer NOT NULL, "id_rol" integer NOT NULL, CONSTRAINT "PK_cc28ffbe77be599168e1ec8670a" PRIMARY KEY ("id_usuario", "id_rol"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6adca3617fc69b2864e67196f2" ON "usuario_rol" ("id_usuario") `);
        await queryRunner.query(`CREATE INDEX "IDX_96d2a6ecb2ad0931416610845c" ON "usuario_rol" ("id_rol") `);
        await queryRunner.query(`CREATE TABLE "proyecto_etiqueta" ("id_proyecto" integer NOT NULL, "id_etiqueta" integer NOT NULL, CONSTRAINT "PK_afd865d4c5fbb38edde3702f2c3" PRIMARY KEY ("id_proyecto", "id_etiqueta"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a1387e6b95efce03d26a32affd" ON "proyecto_etiqueta" ("id_proyecto") `);
        await queryRunner.query(`CREATE INDEX "IDX_b7b5a0ea9ea17b74a346677bb6" ON "proyecto_etiqueta" ("id_etiqueta") `);
        await queryRunner.query(`ALTER TABLE "sesion" ADD CONSTRAINT "FK_7d073f65760a3be0c92ed846c93" FOREIGN KEY ("id_usuario") REFERENCES "usuario"("id_usuario") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_guardado" ADD CONSTRAINT "FK_aa069f8c33f89f0b9e9bd872bba" FOREIGN KEY ("id_usuario") REFERENCES "usuario"("id_usuario") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "archivo_proyecto" ADD CONSTRAINT "FK_13dd61c484544eb240b0d8553a8" FOREIGN KEY ("id_proyecto") REFERENCES "proyecto"("id_proyecto") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "curaduria" ADD CONSTRAINT "FK_be08e479aab1bdc7cc7b6478006" FOREIGN KEY ("id_proyecto") REFERENCES "proyecto"("id_proyecto") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "curaduria" ADD CONSTRAINT "FK_5f37dcfce10d94749c0a516936b" FOREIGN KEY ("id_auxiliar") REFERENCES "usuario"("id_usuario") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "proyecto" ADD CONSTRAINT "FK_b1da223ef12513f5135e083071b" FOREIGN KEY ("id_usuario") REFERENCES "usuario"("id_usuario") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "proyecto" ADD CONSTRAINT "FK_2c96f66dc567ede92effa876a8a" FOREIGN KEY ("id_categoria") REFERENCES "categoria"("id_categoria") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categoria" ADD CONSTRAINT "FK_e41da9f36cf31d9c01636b3a378" FOREIGN KEY ("id_categoria_padre") REFERENCES "categoria"("id_categoria") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reporte" ADD CONSTRAINT "FK_b176cdbdb236ad642a9eb203812" FOREIGN KEY ("id_reportador") REFERENCES "usuario"("id_usuario") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reporte" ADD CONSTRAINT "FK_49a42439162ca481a7fb9fb6a29" FOREIGN KEY ("id_hilo") REFERENCES "hilo_foro"("id_hilo") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reporte" ADD CONSTRAINT "FK_a680a40e62a89fc6815f1c8df62" FOREIGN KEY ("id_comentario") REFERENCES "comentario"("id_comentario") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reporte" ADD CONSTRAINT "FK_aca7331dcd0e2cee6e92b29408e" FOREIGN KEY ("id_proyecto") REFERENCES "proyecto"("id_proyecto") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reporte" ADD CONSTRAINT "FK_81a7e7c8564f239aa08e2190237" FOREIGN KEY ("id_moderador") REFERENCES "usuario"("id_usuario") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hilo_foro" ADD CONSTRAINT "FK_7e188e618bd1c5f51414618f67c" FOREIGN KEY ("id_usuario") REFERENCES "usuario"("id_usuario") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hilo_foro" ADD CONSTRAINT "FK_78ec7e0642ce9616882eaf89aca" FOREIGN KEY ("id_categoria") REFERENCES "categoria"("id_categoria") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comentario" ADD CONSTRAINT "FK_c28516f059447f007f416d060ab" FOREIGN KEY ("id_usuario") REFERENCES "usuario"("id_usuario") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comentario" ADD CONSTRAINT "FK_3906c661bcbc335529b0983d98d" FOREIGN KEY ("id_hilo") REFERENCES "hilo_foro"("id_hilo") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comentario" ADD CONSTRAINT "FK_1e4252602f59cd5f0807000e1d5" FOREIGN KEY ("id_articulo") REFERENCES "articulo"("id_articulo") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comentario" ADD CONSTRAINT "FK_091c3a41b05ffb186c34b22a621" FOREIGN KEY ("id_comentario_padre") REFERENCES "comentario"("id_comentario") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "articulo" ADD CONSTRAINT "FK_bc6bee1eba43f4761b689532109" FOREIGN KEY ("id_autor") REFERENCES "usuario"("id_usuario") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "valoracion" ADD CONSTRAINT "FK_492624464a1508eec79269473a0" FOREIGN KEY ("id_usuario") REFERENCES "usuario"("id_usuario") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "valoracion" ADD CONSTRAINT "FK_a632845ecac41e9feecbd6adfcd" FOREIGN KEY ("id_hilo") REFERENCES "hilo_foro"("id_hilo") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "valoracion" ADD CONSTRAINT "FK_8b188f126bd45fac865a6a3600b" FOREIGN KEY ("id_comentario") REFERENCES "comentario"("id_comentario") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "valoracion" ADD CONSTRAINT "FK_6753e36072feebf961ec03938c8" FOREIGN KEY ("id_articulo") REFERENCES "articulo"("id_articulo") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "proyecto_vista" ADD CONSTRAINT "FK_109812c00559cda8b1368846695" FOREIGN KEY ("id_proyecto") REFERENCES "proyecto"("id_proyecto") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "proyecto_vista" ADD CONSTRAINT "FK_8e5b94e3fdfeee24db7c596329b" FOREIGN KEY ("id_usuario") REFERENCES "usuario"("id_usuario") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "password_reset" ADD CONSTRAINT "FK_8a3f1ef9624c08d697676d5c3f2" FOREIGN KEY ("id_usuario") REFERENCES "usuario"("id_usuario") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuario_suspension" ADD CONSTRAINT "FK_4e67864fae11a64d22b5ea6c263" FOREIGN KEY ("id_usuario") REFERENCES "usuario"("id_usuario") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuario_suspension" ADD CONSTRAINT "FK_3fae5e55e729d12d9c18ebc621e" FOREIGN KEY ("id_admin") REFERENCES "usuario"("id_usuario") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin_audit" ADD CONSTRAINT "FK_e9a007af59c9a03d1c4280aef17" FOREIGN KEY ("id_admin") REFERENCES "usuario"("id_usuario") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuario_rol" ADD CONSTRAINT "FK_6adca3617fc69b2864e67196f2a" FOREIGN KEY ("id_usuario") REFERENCES "usuario"("id_usuario") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "usuario_rol" ADD CONSTRAINT "FK_96d2a6ecb2ad0931416610845cf" FOREIGN KEY ("id_rol") REFERENCES "rol"("id_rol") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "proyecto_etiqueta" ADD CONSTRAINT "FK_a1387e6b95efce03d26a32affde" FOREIGN KEY ("id_proyecto") REFERENCES "proyecto"("id_proyecto") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "proyecto_etiqueta" ADD CONSTRAINT "FK_b7b5a0ea9ea17b74a346677bb69" FOREIGN KEY ("id_etiqueta") REFERENCES "etiqueta"("id_etiqueta") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "proyecto_etiqueta" DROP CONSTRAINT "FK_b7b5a0ea9ea17b74a346677bb69"`);
        await queryRunner.query(`ALTER TABLE "proyecto_etiqueta" DROP CONSTRAINT "FK_a1387e6b95efce03d26a32affde"`);
        await queryRunner.query(`ALTER TABLE "usuario_rol" DROP CONSTRAINT "FK_96d2a6ecb2ad0931416610845cf"`);
        await queryRunner.query(`ALTER TABLE "usuario_rol" DROP CONSTRAINT "FK_6adca3617fc69b2864e67196f2a"`);
        await queryRunner.query(`ALTER TABLE "admin_audit" DROP CONSTRAINT "FK_e9a007af59c9a03d1c4280aef17"`);
        await queryRunner.query(`ALTER TABLE "usuario_suspension" DROP CONSTRAINT "FK_3fae5e55e729d12d9c18ebc621e"`);
        await queryRunner.query(`ALTER TABLE "usuario_suspension" DROP CONSTRAINT "FK_4e67864fae11a64d22b5ea6c263"`);
        await queryRunner.query(`ALTER TABLE "password_reset" DROP CONSTRAINT "FK_8a3f1ef9624c08d697676d5c3f2"`);
        await queryRunner.query(`ALTER TABLE "proyecto_vista" DROP CONSTRAINT "FK_8e5b94e3fdfeee24db7c596329b"`);
        await queryRunner.query(`ALTER TABLE "proyecto_vista" DROP CONSTRAINT "FK_109812c00559cda8b1368846695"`);
        await queryRunner.query(`ALTER TABLE "valoracion" DROP CONSTRAINT "FK_6753e36072feebf961ec03938c8"`);
        await queryRunner.query(`ALTER TABLE "valoracion" DROP CONSTRAINT "FK_8b188f126bd45fac865a6a3600b"`);
        await queryRunner.query(`ALTER TABLE "valoracion" DROP CONSTRAINT "FK_a632845ecac41e9feecbd6adfcd"`);
        await queryRunner.query(`ALTER TABLE "valoracion" DROP CONSTRAINT "FK_492624464a1508eec79269473a0"`);
        await queryRunner.query(`ALTER TABLE "articulo" DROP CONSTRAINT "FK_bc6bee1eba43f4761b689532109"`);
        await queryRunner.query(`ALTER TABLE "comentario" DROP CONSTRAINT "FK_091c3a41b05ffb186c34b22a621"`);
        await queryRunner.query(`ALTER TABLE "comentario" DROP CONSTRAINT "FK_1e4252602f59cd5f0807000e1d5"`);
        await queryRunner.query(`ALTER TABLE "comentario" DROP CONSTRAINT "FK_3906c661bcbc335529b0983d98d"`);
        await queryRunner.query(`ALTER TABLE "comentario" DROP CONSTRAINT "FK_c28516f059447f007f416d060ab"`);
        await queryRunner.query(`ALTER TABLE "hilo_foro" DROP CONSTRAINT "FK_78ec7e0642ce9616882eaf89aca"`);
        await queryRunner.query(`ALTER TABLE "hilo_foro" DROP CONSTRAINT "FK_7e188e618bd1c5f51414618f67c"`);
        await queryRunner.query(`ALTER TABLE "reporte" DROP CONSTRAINT "FK_81a7e7c8564f239aa08e2190237"`);
        await queryRunner.query(`ALTER TABLE "reporte" DROP CONSTRAINT "FK_aca7331dcd0e2cee6e92b29408e"`);
        await queryRunner.query(`ALTER TABLE "reporte" DROP CONSTRAINT "FK_a680a40e62a89fc6815f1c8df62"`);
        await queryRunner.query(`ALTER TABLE "reporte" DROP CONSTRAINT "FK_49a42439162ca481a7fb9fb6a29"`);
        await queryRunner.query(`ALTER TABLE "reporte" DROP CONSTRAINT "FK_b176cdbdb236ad642a9eb203812"`);
        await queryRunner.query(`ALTER TABLE "categoria" DROP CONSTRAINT "FK_e41da9f36cf31d9c01636b3a378"`);
        await queryRunner.query(`ALTER TABLE "proyecto" DROP CONSTRAINT "FK_2c96f66dc567ede92effa876a8a"`);
        await queryRunner.query(`ALTER TABLE "proyecto" DROP CONSTRAINT "FK_b1da223ef12513f5135e083071b"`);
        await queryRunner.query(`ALTER TABLE "curaduria" DROP CONSTRAINT "FK_5f37dcfce10d94749c0a516936b"`);
        await queryRunner.query(`ALTER TABLE "curaduria" DROP CONSTRAINT "FK_be08e479aab1bdc7cc7b6478006"`);
        await queryRunner.query(`ALTER TABLE "archivo_proyecto" DROP CONSTRAINT "FK_13dd61c484544eb240b0d8553a8"`);
        await queryRunner.query(`ALTER TABLE "material_guardado" DROP CONSTRAINT "FK_aa069f8c33f89f0b9e9bd872bba"`);
        await queryRunner.query(`ALTER TABLE "sesion" DROP CONSTRAINT "FK_7d073f65760a3be0c92ed846c93"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b7b5a0ea9ea17b74a346677bb6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a1387e6b95efce03d26a32affd"`);
        await queryRunner.query(`DROP TABLE "proyecto_etiqueta"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_96d2a6ecb2ad0931416610845c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6adca3617fc69b2864e67196f2"`);
        await queryRunner.query(`DROP TABLE "usuario_rol"`);
        await queryRunner.query(`DROP TABLE "admin_audit"`);
        await queryRunner.query(`DROP TABLE "usuario_suspension"`);
        await queryRunner.query(`DROP TABLE "password_reset"`);
        await queryRunner.query(`DROP TABLE "proyecto_vista"`);
        await queryRunner.query(`DROP TABLE "valoracion"`);
        await queryRunner.query(`DROP TYPE "public"."valoracion_tipo_enum"`);
        await queryRunner.query(`DROP TABLE "articulo"`);
        await queryRunner.query(`DROP TYPE "public"."articulo_estado_enum"`);
        await queryRunner.query(`DROP TABLE "comentario"`);
        await queryRunner.query(`DROP TABLE "hilo_foro"`);
        await queryRunner.query(`DROP TYPE "public"."hilo_foro_estado_enum"`);
        await queryRunner.query(`DROP TABLE "reporte"`);
        await queryRunner.query(`DROP TYPE "public"."reporte_estado_enum"`);
        await queryRunner.query(`DROP TABLE "categoria"`);
        await queryRunner.query(`DROP TYPE "public"."categoria_area_tecnica_enum"`);
        await queryRunner.query(`DROP TABLE "proyecto"`);
        await queryRunner.query(`DROP TYPE "public"."proyecto_estado_enum"`);
        await queryRunner.query(`DROP TABLE "etiqueta"`);
        await queryRunner.query(`DROP TABLE "curaduria"`);
        await queryRunner.query(`DROP TABLE "archivo_proyecto"`);
        await queryRunner.query(`DROP TABLE "usuario"`);
        await queryRunner.query(`DROP TABLE "material_guardado"`);
        await queryRunner.query(`DROP TYPE "public"."material_guardado_tipo_contenido_enum"`);
        await queryRunner.query(`DROP TABLE "sesion"`);
        await queryRunner.query(`DROP TABLE "rol"`);
    }

}
